plugins {
    id 'com.android.application'
}

android {
    namespace 'eg.outbox.app'
    compileSdk 34

    defaultConfig {
        applicationId "eg.outbox.smartgreenschool"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // Pure Native Zero-Dependency Android Implementation
}
